### PR TITLE
[BLD-688] meta package must depends on subpackages with version

### PR DESCRIPTION
**Pull request by EvgeniyPatlan**

### CODE REVIEW

**Comment by tplavcic** [comment]
please check with Denis if this needs to go to the master branch also

**Comment by denis-protyvenskyi** [comment]
I'll port to the master, do we need this for 3.2?

**Comment by denis-protyvenskyi** [comment]
Looks like it's in 3.2, and I forgot to port it: https://github.com/percona/percona-server-mongodb/pull/152

**Comment by tplavcic** [comment]
Yes it was in 3.2, so this time it's 3.4 only and master branch.

**Pull request merged**
