### PR TITLE
PSMDB should help setup user on interactive startups

### PR DESCRIPTION
**Pull request by EvgeniyPatlan**

### CODE REVIEW

**Comment by denis-protyvenskyi** [comment]
Isn't it a good time to take this functionality out into a separate file?

**Comment by tplavcic** [comment]
@denis-protyvenskyi but percona-server-mongodb-helper.sh is already a separate file (helper functionality moved away from our init scripts), so our init scripts use this helper script for various things and it's used in sysvinit and systemd also, if we add another we'll have to use two helper scripts in init scripts.
@EvgeniyPatlan is ti possible to build packages with this functionality and push them into experimental repository so they can be tested?

**Comment by EvgeniyPatlan** [comment]
@tplavcic the packages are already built. I'm going to push them into experimental repo and inform you once it is done

**Comment by denis-protyvenskyi** [comment]
@tplavcic I propose to `source` another file from this one, so no need to change other scripts. I vote for separating out this because the script already became too heavy.

**Comment by tplavcic** [comment]
@denis-protyvenskyi ok, I have no preference so if you and Evgeniy agree to separate it I'm fine with that.
I just want to see how packages work with this because I have some doubts at least for systemd so this is my main concern.

**Comment by EvgeniyPatlan** [comment]
Updated

**Comment by EvgeniyPatlan** [comment]
This solution doesn't work for systemd

**Pull request closed without merging**
