### PR TITLE
Percona packaging for v3.4

### PR DESCRIPTION
**Pull request by denis-protyvenskyi**
Just cherry-picking all the commits from v3.2, will need to clean up the folder later.

### CODE REVIEW

**Comment by denis-protyvenskyi** [comment]
This one also needs https://github.com/percona/percona-server-mongodb/pull/134 to be included when it gets merged.

**Comment by denis-protyvenskyi** [comment]
Cherry-picked https://github.com/percona/percona-server-mongodb/pull/137

**Comment by denis-protyvenskyi** [comment]
Cherry-picked https://github.com/percona/percona-server-mongodb/pull/134

**Comment by tplavcic** [comment]
LGTM, from now on, all changes should be evaluated for 3.2 and then merged to 3.4 but 3.4 needs a cleanup first (files renaming for new version for one thing)

**Pull request merged**
