### PR TITLE
[BLD-741] PSMDB on centos 7 is not enabled

### PR DESCRIPTION
**Pull request by EvgeniyPatlan**
(cherry picked from commit 8a87d7aa8867ec4e1ab16f9d4301df15fce19fe2)

### CODE REVIEW

**Comment by EvgeniyPatlan** [comment]
fixed

**Comment by tplavcic** [comment]
Sorry, I made a mistake, in PS it's part of `preun` not `postun`:
```
 545 %preun -n Percona-Server-server%{product_suffix}
 546 %if 0%{?systemd}
 547 %systemd_preun mysqld.service
 548 %else
 549 if [ "$1" = 0 ]; then
 550     /sbin/service mysql stop >/dev/null 2>&1 || :
 551     /sbin/chkconfig --del mysql
 552 fi
 553 %endif
```
Not sure would it make some real difference or not, but let's keep it the same.

**Comment by EvgeniyPatlan** [comment]
fixed

**Comment by denis-protivenskii** [comment]
This needs cherry-picking from v3.4 commit after it has changed. I'll open another PR by myself.

**Pull request closed without merging**
