### PR TITLE
Added template for storage engine configurations in mongod.conf (PSMDB-83)

### PR DESCRIPTION
**Pull request by tplavcic**
**Ticket: PSMDB-83**
Added basic template for storage engine configurations in mongod.conf so that people can start customizing it more easily.

### CODE REVIEW

**Comment by igorsol** [comment]
LGTM

**Comment by tplavcic** [comment]
As agreed on the meeting, I'll test the settings for every storage engine to see that the server can actually run with it. So this can't be merged before this is tested.

**Comment by dbpercona** [comment]
+1

**Comment by dbmurphy** [comment]
Can we have @timvaillancourt review these levels? I know they are the defaults,  however, should we maybe add comments if we think the settings might sometimes need to be something else. For example on a busy system they might need more transactions allowed or a lower memory limit due to the over-allocation bugs.

**Comment by timvaillancourt** [comment]
Thanks @tplavcic, a few things I think we should fix:

1. As of 3.2 the WiredTiger (and thus probably InMemory) cache default is 60% of RAM minus 1GB or 1GB: https://docs.mongodb.com/v3.2/faq/storage/#wiredtiger-storage-engine. I think we should make '1' the default for the cache value in our examples due to this. For consistency I think RocksDB can also default to 1GB and PerconaFT can stay as-is.

2. I believe we should be including the concurrentTransaction Read/Write limits (both default to 128), which is a commonly tuned variable. The setParameters for this is wiredTigerConcurrentReadTransactions and wiredTigerConcurrentWriteTransactions but I cannot seem to find the yaml config path, but I know it can be set under storage.wiredTiger somehow.

Lastly, I think we should document warnings/disclaimers for the following defaults wherever possible to help users make good decisions and understand these settings aren't for every situation:

1. The 128 defaults for concurrentTransactions in WT may need adjustment on very high volume systems.
2. Systems with more than roughly 24,000 collections will need an increased 'nsSize' variable.
3. Use storage.mmapv1.smallFiles set to 'true' if you have a large number of databases that each holds a small quantity of data.
4. storage.rocksdb.counters must be set to 'true' when using Percona Monitoring & Management with RocksDB. We should also mention 'true' will become the default at some point in 3.4 due to this change: https://github.com/mongodb-partners/mongo-rocks/commit/8bb384fb27f781e5f36e544df36aa7bb4b46b28a

Overall it looks good to me 👍

**Comment by tplavcic** [comment]
Thanks @timvaillancourt I've made the changes you requested:
1. changed `cacheSizeGB: 1` for wiredTiger and rocksdb and `inMemorySizeGB: 1` for inMemory
2. I have added the following after the section for all engines:
```
# Two options below can be used for wiredTiger and inMemory storage engines
#setParameter:
#    wiredTigerConcurrentReadTransactions: 128
#    wiredTigerConcurrentWriteTransactions: 128
```
I couldn't find the more appropriate yaml path except for using the setParameter in the config. Also Denis has commented that the same two options can be used for inMemory thus I have put this after all storage engines settings and made a comment that those two options can be used for WT and inMemory.

For the documentation part I will open a DOC ticket in Jira so that it is documented on the webpage but only when you confirm that this template is ok.
After that I will also test it with every storage engine to make sure it runs before the merge.

So please comment if it's now ok or not?

**Comment by timvaillancourt** [comment]
Thanks @tplavcic, I think this is good now!

**Comment by tplavcic** [comment]
For those interested I have opened the DOC ticket here: https://jira.percona.com/browse/DOC-327
Most probably if new page is created I'll need to add that link into the config file itself but that can be done later as it's not that problematic.

Also I have tested the configurations and didn't face issues:
**DEFAULT**
```
ubuntu@t-ubuntu1604-64:~$ mongo --eval "db.serverStatus().storageEngine"
MongoDB shell version: 3.2.10-3.0
connecting to: test
{
        "name" : "wiredTiger",
        "supportsCommittedReads" : true,
        "persistent" : true
}

ubuntu@t-ubuntu1604-64:~$ mongo --eval "db.serverCmdLineOpts()"
MongoDB shell version: 3.2.10-3.0
connecting to: test
{
        "argv" : [
                "/usr/bin/mongod",
                "-f",
                "/etc/mongod.conf"
        ],
        "parsed" : {
                "config" : "/etc/mongod.conf",
                "net" : {
                        "bindIp" : "127.0.0.1",
                        "port" : 27017
                },
                "processManagement" : {
                        "fork" : true,
                        "pidFilePath" : "/var/run/mongod.pid"
                },
                "storage" : {
                        "dbPath" : "/var/lib/mongodb",
                        "journal" : {
                                "enabled" : true
                        }
                },
                "systemLog" : {
                        "destination" : "file",
                        "logAppend" : true,
                        "path" : "/var/log/mongodb/mongod.log"
                }
        },
        "ok" : 1
}
```

**MMAPv1**
```
ubuntu@t-ubuntu1604-64:~$ mongo --eval "db.serverStatus().storageEngine"
MongoDB shell version: 3.2.10-3.0
connecting to: test
{ "name" : "mmapv1", "supportsCommittedReads" : false, "persistent" : true }

ubuntu@t-ubuntu1604-64:~$ mongo --eval "db.serverCmdLineOpts()"
MongoDB shell version: 3.2.10-3.0
connecting to: test
{
        "argv" : [
                "/usr/bin/mongod",
                "-f",
                "/etc/mongod.conf"
        ],
        "parsed" : {
                "config" : "/etc/mongod.conf",
                "net" : {
                        "bindIp" : "127.0.0.1",
                        "port" : 27017
                },
                "processManagement" : {
                        "fork" : true,
                        "pidFilePath" : "/var/run/mongod.pid"
                },
                "storage" : {
                        "dbPath" : "/var/lib/mongodb",
                        "engine" : "mmapv1",
                        "journal" : {
                                "enabled" : true
                        },
                        "mmapv1" : {
                                "nsSize" : 16,
                                "preallocDataFiles" : true,
                                "quota" : {
                                        "enforced" : false,
                                        "maxFilesPerDB" : 8
                                },
                                "smallFiles" : false
                        }
                },
                "systemLog" : {
                        "destination" : "file",
                        "logAppend" : true,
                        "path" : "/var/log/mongodb/mongod.log"
                }
        },
        "ok" : 1
}

Error log:
2016-11-16T10:40:43.822+0000 I CONTROL  [initandlisten] options: { config: "/etc/mongod.conf", net: { bindIp: "127.0.0.1", port: 27017 }, processManagement: { fork: true, pidFilePath: "/var/run/mongod.pid" }, storage: { dbPath: "/var/lib/mongodb", engine: "mmapv1", journal: { enabled: true }, mmapv1: { nsSize: 16, preallocDataFiles: true, quota: { enforced: false, maxFilesPerDB: 8 }, smallFiles: false } }, systemLog: { destination: "file", logAppend: true, path: "/var/log/mongodb/mongod.log" } }
```

**wiredTiger**
```
MongoDB shell version: 3.2.10-3.0
connecting to: test
{
        "name" : "wiredTiger",
        "supportsCommittedReads" : true,
        "persistent" : true
}

ubuntu@t-ubuntu1604-64:~$ mongo --eval "db.serverCmdLineOpts()"
MongoDB shell version: 3.2.10-3.0
connecting to: test
{
        "argv" : [
                "/usr/bin/mongod",
                "-f",
                "/etc/mongod.conf"
        ],
        "parsed" : {
                "config" : "/etc/mongod.conf",
                "net" : {
                        "bindIp" : "127.0.0.1",
                        "port" : 27017
                },
                "processManagement" : {
                        "fork" : true,
                        "pidFilePath" : "/var/run/mongod.pid"
                },
                "setParameter" : {
                        "wiredTigerConcurrentReadTransactions" : "128",
                        "wiredTigerConcurrentWriteTransactions" : "128"
                },
                "storage" : {
                        "dbPath" : "/var/lib/mongodb",
                        "engine" : "wiredTiger",
                        "journal" : {
                                "enabled" : true
                        },
                        "wiredTiger" : {
                                "collectionConfig" : {
                                        "blockCompressor" : "snappy"
                                },
                                "engineConfig" : {
                                        "cacheSizeGB" : 1,
                                        "directoryForIndexes" : false,
                                        "journalCompressor" : "snappy",
                                        "statisticsLogDelaySecs" : 0
                                },
                                "indexConfig" : {
                                        "prefixCompression" : true
                                }
                        }
                },
                "systemLog" : {
                        "destination" : "file",
                        "logAppend" : true,
                        "path" : "/var/log/mongodb/mongod.log"
                }
        },
        "ok" : 1
}

Error log:
2016-11-16T10:45:24.362+0000 I CONTROL  [initandlisten] options: { config: "/etc/mongod.conf", net: { bindIp: "127.0.0.1", port: 27017 }, processManagement: { fork: true, pidFilePath: "/var/run/mongod.pid" }, setParameter: { wiredTigerConcurrentReadTransactions: "128", wiredTigerConcurrentWriteTransactions: "128" }, storage: { dbPath: "/var/lib/mongodb", engine: "wiredTiger", journal: { enabled: true }, wiredTiger: { collectionConfig: { blockCompressor: "snappy" }, engineConfig: { cacheSizeGB: 1, directoryForIndexes: false, journalCompressor: "snappy", statisticsLogDelaySecs: 0 }, indexConfig: { prefixCompression: true } } }, systemLog: { destination: "file", logAppend: true, path: "/var/log/mongodb/mongod.log" } }
```

**rocksdb**
```
ubuntu@t-ubuntu1604-64:~$ mongo --eval "db.serverStatus().storageEngine"
MongoDB shell version: 3.2.10-3.0
connecting to: test
{ "name" : "rocksdb", "supportsCommittedReads" : true, "persistent" : true }

ubuntu@t-ubuntu1604-64:~$ mongo --eval "db.serverCmdLineOpts()"
MongoDB shell version: 3.2.10-3.0
connecting to: test
{
        "argv" : [
                "/usr/bin/mongod",
                "-f",
                "/etc/mongod.conf"
        ],
        "parsed" : {
                "config" : "/etc/mongod.conf",
                "net" : {
                        "bindIp" : "127.0.0.1",
                        "port" : 27017
                },
                "processManagement" : {
                        "fork" : true,
                        "pidFilePath" : "/var/run/mongod.pid"
                },
                "storage" : {
                        "dbPath" : "/var/lib/mongodb",
                        "engine" : "rocksdb",
                        "journal" : {
                                "enabled" : true
                        },
                        "rocksdb" : {
                                "cacheSizeGB" : 1,
                                "compression" : "snappy",
                                "counters" : false,
                                "crashSafeCounters" : false,
                                "maxWriteMBPerSec" : 1024,
                                "singleDeleteIndex" : false
                        }
                },
                "systemLog" : {
                        "destination" : "file",
                        "logAppend" : true,
                        "path" : "/var/log/mongodb/mongod.log"
                }
        },
        "ok" : 1
}

Error log:
2016-11-16T11:27:52.390+0000 I CONTROL  [initandlisten] options: { config: "/etc/mongod.conf", net: { bindIp: "127.0.0.1", port: 27017 }, processManagement: { fork: true, pidFilePath: "/var/run/mongod.pid" }, storage: { dbPath: "/var/lib/mongodb", engine: "rocksdb", journal: { enabled: true }, rocksdb: { cacheSizeGB: 1, compression: "snappy", counters: false, crashSafeCounters: false, maxWriteMBPerSec: 1024, singleDeleteIndex: false } }, systemLog: { destination: "file", logAppend: true, path: "/var/log/mongodb/mongod.log" } }
```

**inMemory**
```
ubuntu@t-ubuntu1604-64:~$ mongo --eval "db.serverStatus().storageEngine"
MongoDB shell version: 3.2.10-3.0
connecting to: test
{
        "name" : "inMemory",
        "supportsCommittedReads" : true,
        "persistent" : false
}

ubuntu@t-ubuntu1604-64:~$ mongo --eval "db.serverCmdLineOpts()"
MongoDB shell version: 3.2.10-3.0
connecting to: test
{
        "argv" : [
                "/usr/bin/mongod",
                "-f",
                "/etc/mongod.conf"
        ],
        "parsed" : {
                "config" : "/etc/mongod.conf",
                "net" : {
                        "bindIp" : "127.0.0.1",
                        "port" : 27017
                },
                "processManagement" : {
                        "fork" : true,
                        "pidFilePath" : "/var/run/mongod.pid"
                },
                "setParameter" : {
                        "wiredTigerConcurrentReadTransactions" : "128",
                        "wiredTigerConcurrentWriteTransactions" : "128"
                },
                "storage" : {
                        "dbPath" : "/var/lib/mongodb",
                        "engine" : "inMemory",
                        "inMemory" : {
                                "engineConfig" : {
                                        "inMemorySizeGB" : 1,
                                        "statisticsLogDelaySecs" : 0
                                }
                        },
                        "journal" : {
                                "enabled" : true
                        }
                },
                "systemLog" : {
                        "destination" : "file",
                        "logAppend" : true,
                        "path" : "/var/log/mongodb/mongod.log"
                }
        },
        "ok" : 1
}

Error log:
2016-11-16T10:55:56.147+0000 I CONTROL  [initandlisten] options: { config: "/etc/mongod.conf", net: { bindIp: "127.0.0.1", port: 27017 }, processManagement: { fork: true, pidFilePath: "/var/run/mongod.pid" }, setParameter: { wiredT
igerConcurrentReadTransactions: "128", wiredTigerConcurrentWriteTransactions: "128" }, storage: { dbPath: "/var/lib/mongodb", engine: "inMemory", inMemory: { engineConfig: { inMemorySizeGB: 1.0, statisticsLogDelaySecs: 0 } }, journ
al: { enabled: true } }, systemLog: { destination: "file", logAppend: true, path: "/var/log/mongodb/mongod.log" } }
```

**PerconaFT**
```
ubuntu@t-ubuntu1604-64:~$ mongo --eval "db.serverStatus().storageEngine"
MongoDB shell version: 3.2.10-3.0
connecting to: test
{
        "name" : "PerconaFT",
        "supportsCommittedReads" : false,
        "persistent" : true
}

ubuntu@t-ubuntu1604-64:~$ mongo --eval "db.serverCmdLineOpts()"
MongoDB shell version: 3.2.10-3.0
connecting to: test
{
        "argv" : [
                "/usr/bin/mongod",
                "-f",
                "/etc/mongod.conf"
        ],
        "parsed" : {
                "config" : "/etc/mongod.conf",
                "net" : {
                        "bindIp" : "127.0.0.1",
                        "port" : 27017
                },
                "processManagement" : {
                        "fork" : true,
                        "pidFilePath" : "/var/run/mongod.pid"
                },
                "storage" : {
                        "PerconaFT" : {
                                "collectionOptions" : {
                                        "compression" : "zlib",
                                        "fanout" : 16,
                                        "pageSize" : 4194304,
                                        "readPageSize" : 65536
                                },
                                "engineOptions" : {
                                        "cacheSize" : 0,
                                        "cleanerIterations" : 5,
                                        "cleanerPeriod" : 2,
                                        "compressBuffersBeforeEviction" : false,
                                        "directio" : false,
                                        "fsRedzone" : 5,
                                        "journalCommitInterval" : 100,
                                        "lockTimeout" : 100,
                                        "locktreeMaxMemory" : 0,
                                        "numCachetableBucketMutexes" : 1048576
                                },
                                "indexOptions" : {
                                        "compression" : "zlib",
                                        "fanout" : 16,
                                        "pageSize" : 4194304,
                                        "readPageSize" : 65536
                                }
                        },
                        "dbPath" : "/var/lib/mongodb",
                        "engine" : "PerconaFT",
                        "journal" : {
                                "enabled" : true
                        }
                },
                "systemLog" : {
                        "destination" : "file",
                        "logAppend" : true,
                        "path" : "/var/log/mongodb/mongod.log"
                }
        },
        "ok" : 1
}

Error log:
2016-11-16T11:02:38.101+0000 I CONTROL  [initandlisten] options: { config: "/etc/mongod.conf", net: { bindIp: "127.0.0.1", port: 27017 }, processManagement: { fork: true, pidFilePath: "/var/run/mongod.pid" }, storage: { PerconaFT: { collectionOptions: { compression: "zlib", fanout: 16, pageSize: 4194304, readPageSize: 65536 }, engineOptions: { cacheSize: 0, cleanerIterations: 5, cleanerPeriod: 2, compressBuffersBeforeEviction: false, directio: false, fsRedzone: 5, journalCommitInterval: 100, lockTimeout: 100, locktreeMaxMemory: 0, numCachetableBucketMutexes: 1048576 }, indexOptions: { compression: "zlib", fanout: 16, pageSize: 4194304, readPageSize: 65536 } }, dbPath: "/var/lib/mongodb", engine: "PerconaFT", journal: { enabled: true } }, systemLog: { destination: "file", logAppend: true, path: "/var/log/mongodb/mongod.log" } }
```

**Pull request merged**
