### PR TITLE
Use mongotools from the same repo

### PR DESCRIPTION
**Pull request by EvgeniyPatlan**
Use https://github.com/percona/percona-server-mongodb/tree/master/src/mongo/gotools for building mongo tools so we don't need to checkout separate repository

### CODE REVIEW

**Comment by EvgeniyPatlan** [comment]
@tplavcic sure. I will do this

**Comment by dbmurphy** [comment]
We should be cloning this for future needs as we are going to need to fork this very soon to support encrypted dump backups. 

As such should we really be doing this just to undo it later?

David murphy

**Comment by tplavcic** [comment]
Valid question for @denis-protyvenskyi ^^^

**Comment by denis-protyvenskyi** [comment]
Decided to keep as it is for now.

**Pull request closed without merging**
