### PR TITLE
Support numa interleaving on Systemd-based Redhat/CentOS hosts

### PR DESCRIPTION
**Pull request by timvaillancourt**
Merged over SERVER-3574 from MongoDB Inc into our systemd-based init scripts. We will now start mongod with 'numactl --interleave=all' if numactl exists.

This was already supported in mongod.init (for non-systemd-based RPMs that use /etc/init.d for init scripts), seen here: https://github.com/percona/percona-server-mongodb/blob/v3.2/percona-packaging/redhat/mongod.init. Only systemd-based hosts are missing this change, so I moved the logic down to /usr/bin/percona-server-mongodb-helper.sh, called by all RPMs on startup (systemd or not).

Redhat/CentOS RPMs will require the 'numactl' package to achieve this (added to Requires: in .spec file).

### CODE REVIEW

**Comment by timvaillancourt** [comment]
Good question @tplavcic. If debian is also doing this in another script, it will get set twice. It would probably make sense to remove the logic from debian also if percona-server-mongodb-helper.sh handle it below.

**Comment by timvaillancourt** [comment]
Ok @tplavcic, I've removed the same block from the debian init file and also moved the 'DAEMON_OPTS' variable (that debian's script uses) to the helper also. Please review this now.

**Comment by tplavcic** [comment]
LGTM, but @EvgeniyPatlan needs to check also and approve it.

**Comment by EvgeniyPatlan** [comment]
LGTM

**Pull request merged**
