### PR TITLE
There is no conflict between 3.2 and 3.4 packages

### PR DESCRIPTION
**Pull request by EvgeniyPatlan**

### CODE REVIEW

**Comment by tplavcic** [comment]
Although this is needed on the master branch also, I think you should have first done the change on the master branch and then @denis-protyvenskyi moves those changes to 3.4 branch.

**Comment by EvgeniyPatlan** [comment]
@tplavcic  I have changed the commit branch to master. So let's wait for Denis.

**Comment by denis-protyvenskyi** [comment]
@EvgeniyPatlan is it ok that for Redhat there's no `percona-server-mongodb-32-dbg` package as for Debian?

**Comment by EvgeniyPatlan** [comment]
it is ok for redhat.

**Comment by tplavcic** [comment]
@denis-protyvenskyi RPM packages have "debuginfo" package.

**Pull request merged**
